### ISSUE TITLE
ZEO absent from 6.0.4

### ISSUE THREAD

**Issue by Rudd-O** [plone/plone-backend#119]
Hello!

Our Plone servers use ZEO to run multiple backends within the same Kubernetes pod.

We noticed upon upgrade that the ZEO client libraries are missing from the latest stable published container image (we derive our container images from this one).  The traceback reported it cannot import the `ZEO` module.

Is there a reason why this is missing?

The workaround I have implemented in our container file goes like this:

```
# Add ZEO
RUN /app/bin/pip install -U ZEO -c /app/constraints.txt
```

Tests for the containers using the ZEO library should be added so this does not happen in the future again.

**Comment by erral** [comment]
See https://community.plone.org/t/plone-6-0-4-released/17406/3

**Comment by avoinea** [comment]
```
Using ZEO configuration
Traceback (most recent call last):
  File "/app/bin/runwsgi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 251, in main
    return command.run()
           ^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 200, in invoke
    app = context.app_context.create()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/app/lib/python3.11/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/app/lib/python3.11/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/app/lib/python3.11/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/app/lib/python3.11/site-packages/Zope2/App/startup.py", line 100, in startup
    DB = dbtab.getDatabase('/', is_root=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 245, in getDatabase
    db = factory.open(name, self.databases)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 141, in open
    DB = self.createDB(database_name, databases)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 138, in createDB
    return ZODBDatabase.open(self, databases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/ZODB/config.py", line 146, in open
    storage = section.storage.open()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/ZODB/config.py", line 239, in open
    from ZEO.ClientStorage import ClientStorage
ModuleNotFoundError: No module named 'ZEO'
```
